field: 187580b7-6dbe-4d63-ab88-5288f10e41aa # Handige links
fieldLayouts:
  0e075127-f929-4f4c-9a06-8219f99300f8:
    tabs:
      -
        elements:
          -
            fieldUid: 1949f3e2-18c5-4b9b-9f1a-eef1b436c2c0 # Url webpagina
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dbeeb63e-4eb6-4814-aa18-23e6fe8f3682
            warning: null
            width: 100
        name: Content
        uid: 0bbc3b3f-dd65-494f-abe1-64bd5d6d4b67
fields:
  1949f3e2-18c5-4b9b-9f1a-eef1b436c2c0: # Url webpagina
    columnSuffix: scnksmom
    contentColumnType: string(255)
    fieldGroup: null
    handle: urlLink
    instructions: null
    name: 'Url webpagina'
    searchable: false
    settings:
      maxLength: 255
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
handle: links
name: Linken
sortOrder: 1
