field: c30035de-f5ed-4cd6-92bd-7202cd70701a # Locatie
fieldLayouts:
  c51563bf-fc25-430a-a548-cac5f818f1a8:
    tabs:
      -
        elements:
          -
            fieldUid: e56ad2b8-f25f-47c4-885d-b4a6486b90f0 # Stad
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 48993bd9-599f-40e3-ab39-702c147f17bb
            warning: null
            width: 100
          -
            fieldUid: 2a7bf3bc-6a3a-4ccd-88e2-7dd82ff659a5 # Naam 
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d415c584-ba90-440b-bca5-83ef86a9f909
            warning: null
            width: 100
          -
            fieldUid: d385d78b-b2fe-477f-b2eb-279e466ef378 # Straat + nr.
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6e77e131-92d2-4abf-98ff-5f611784cf9a
            warning: null
            width: 100
          -
            fieldUid: e12094c8-d18a-4e6b-89e0-d868b63c5beb # Postcode + stad
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4f6e2a79-e55a-4a95-81fe-0b754e5e872f
            warning: null
            width: 100
          -
            fieldUid: 515fb477-dae9-4b04-9de1-f31c7e0eac68 # Telefoonnummer
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b29f2c57-5284-4bda-81cb-a37c9176be7d
            warning: null
            width: 100
          -
            fieldUid: 9438f96a-57ec-49c4-a710-41848548afb5 # Google Maps Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c3ecca2c-59fa-470c-b61b-6fdbd2911860
            warning: null
            width: 100
        name: Content
        uid: 130a2a27-db7f-4cb6-89ea-5fbe0d419c7f
fields:
  2a7bf3bc-6a3a-4ccd-88e2-7dd82ff659a5: # Naam 
    columnSuffix: tjfnbyjf
    contentColumnType: text
    fieldGroup: null
    handle: locationName
    instructions: null
    name: 'Naam '
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  515fb477-dae9-4b04-9de1-f31c7e0eac68: # Telefoonnummer
    columnSuffix: sbgdesvy
    contentColumnType: text
    fieldGroup: null
    handle: phoneNumber
    instructions: null
    name: Telefoonnummer
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  9438f96a-57ec-49c4-a710-41848548afb5: # Google Maps Link
    columnSuffix: napxlbez
    contentColumnType: string(255)
    fieldGroup: null
    handle: googleMapsLink
    instructions: null
    name: 'Google Maps Link'
    searchable: false
    settings:
      maxLength: 255
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  d385d78b-b2fe-477f-b2eb-279e466ef378: # Straat + nr.
    columnSuffix: fmffboel
    contentColumnType: text
    fieldGroup: null
    handle: streetNr
    instructions: null
    name: 'Straat + nr.'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e56ad2b8-f25f-47c4-885d-b4a6486b90f0: # Stad
    columnSuffix: ktrulvpv
    contentColumnType: text
    fieldGroup: null
    handle: locationCity
    instructions: null
    name: Stad
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e12094c8-d18a-4e6b-89e0-d868b63c5beb: # Postcode + stad
    columnSuffix: tzheqeqn
    contentColumnType: text
    fieldGroup: null
    handle: postalcodeCity
    instructions: null
    name: 'Postcode + stad'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: location
name: Locatie
sortOrder: 1
