field: 42753f56-881c-4d30-82a4-7062d713de9b # Contentbuilder
fieldLayouts:
  48f73c79-104f-48fb-999e-cdf37c0cffe5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: bf63573b-3a46-45f9-8a05-fe1df00844a8 # Tekst
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 878b2eae-69f1-4abf-bfd5-706fa6987a0f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 49b2e501-f490-423e-bf75-44effe76308b # Achtergrondkleur
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7422e8f1-90c4-452e-9506-567b92682b5b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3607b72b-a3ce-4025-8114-a830e5ba5a7a
        userCondition: null
fields:
  49b2e501-f490-423e-bf75-44effe76308b: # Achtergrondkleur
    columnSuffix: tbtnesiw
    contentColumnType: string
    fieldGroup: null
    handle: bgColor
    instructions: 'Selecteer een kleur voor de achtergrond van dit blok'
    name: Achtergrondkleur
    searchable: false
    settings:
      dataSet: 'Background colors'
      type: dropdown
    translationKeyFormat: null
    translationMethod: none
    type: statikbe\configvaluesfield\fields\ConfigValuesFieldField
  bf63573b-3a46-45f9-8a05-fe1df00844a8: # Tekst
    columnSuffix: opmzhzse
    contentColumnType: text
    fieldGroup: null
    handle: redactor
    instructions: null
    name: Tekst
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Extended.json
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: redactor
name: Tekst
sortOrder: 2
