field: 42753f56-881c-4d30-82a4-7062d713de9b # Contentbuilder
fieldLayouts:
  a613bfaa-ead9-474f-8427-04a8941a6900:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8ae04f87-c29b-40d5-aa85-7eda669ccf72 # Titel
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6301acf5-6970-4ddb-856b-770ec4c2e7e4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fd3e6c44-b090-4050-acd1-f201d539bb8f # Tekst
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e74e702f-e341-4892-9d94-793d7a3d6e77
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b5042dd9-234b-4fc1-b3fd-e04168caeea4 # Werkingsonderdelen
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 64dfbe76-b31e-4667-9deb-0ee187d2daa2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3cc91ca4-2d96-426a-bb90-fc52622494da # Call to action(s)
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4be8ac2a-a381-41b5-a390-51f1d492d8ae
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5e9897d4-a4bb-4a02-9c5e-9f16e26cf9e3 # Achtergrondkleur
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dbc95904-7f98-4b14-aac0-83cfb14ad5d8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 09befa6c-f2f9-45ef-be21-7906e2228ec8
        userCondition: null
fields:
  3cc91ca4-2d96-426a-bb90-fc52622494da: # Call to action(s)
    columnSuffix: fqkqogpg
    contentColumnType: string
    fieldGroup: null
    handle: ctas
    instructions: null
    name: 'Call to action(s)'
    searchable: true
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 295487213
      columns:
        __assoc__:
          -
            - c21b1ead-1dd5-4baf-9631-5d85e05b1936 # Call to action
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_51_ctas}}'
      fieldLayout: matrix
      maxRows: 2
      minRows: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: null
      staticField: null
    translationKeyFormat: null
    translationMethod: none
    type: verbb\supertable\fields\SuperTableField
  5e9897d4-a4bb-4a02-9c5e-9f16e26cf9e3: # Achtergrondkleur
    columnSuffix: ybgyqfti
    contentColumnType: string
    fieldGroup: null
    handle: bgColor
    instructions: 'Selecteer een kleur voor de achtergrond van dit blok'
    name: Achtergrondkleur
    searchable: false
    settings:
      dataSet: 'Background colors'
      type: dropdown
    translationKeyFormat: null
    translationMethod: none
    type: statikbe\configvaluesfield\fields\ConfigValuesFieldField
  8ae04f87-c29b-40d5-aa85-7eda669ccf72: # Titel
    columnSuffix: ypwwtopo
    contentColumnType: text
    fieldGroup: null
    handle: blockTitle
    instructions: null
    name: Titel
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b5042dd9-234b-4fc1-b3fd-e04168caeea4: # Werkingsonderdelen
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: serviceEntries
    instructions: null
    name: Werkingsonderdelen
    searchable: true
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
      selectionLabel: 'Selecteer een onderdeel'
      showSiteMenu: true
      sources:
        - 'section:7ef3951c-2209-42d7-8ece-10077019d52c' # Werking
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  fd3e6c44-b090-4050-acd1-f201d539bb8f: # Tekst
    columnSuffix: akkaxibh
    contentColumnType: text
    fieldGroup: null
    handle: redactor
    instructions: null
    name: Tekst
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: servicesLatest
name: 'Werking overzichtskaarten'
sortOrder: 13
