field: 42753f56-881c-4d30-82a4-7062d713de9b # Contentbuilder
fieldLayouts:
  50f9f6d8-caea-46c7-9b38-2ddf0a7baf7d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e500f71a-4761-4052-92c4-da721c26adc9 # Titel
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 038612b6-229b-451c-a037-e1ee28ed3e6a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2987df5c-9c25-40c8-a296-cbf10cb1ef92
        userCondition: null
fields:
  e500f71a-4761-4052-92c4-da721c26adc9: # Titel
    columnSuffix: yqshvmvo
    contentColumnType: text
    fieldGroup: null
    handle: blockTitle
    instructions: 'Geef een titel in voor dit blok. De doelgroepen zullen dan automatisch weergegeven worden.'
    name: Titel
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: targetGroups
name: Doelgroepen
sortOrder: 10
