field: 073500d7-f6ec-444e-8f0a-650eaa803cb0 # Titel | Tekstblok
fieldLayouts:
  a8b54eef-1721-47bd-9ea9-c6da8259673a:
    tabs:
      -
        elements:
          -
            fieldUid: ab3e3d3a-debc-42ca-a231-3766789addd3 # Titel
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 112e76b7-267e-4f52-a443-6cc34a752d0e
            warning: null
            width: 100
          -
            fieldUid: 510eb9fd-46de-4aa4-8f10-4282c0fb4de8 # Inhoud
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 93be6065-fb82-426c-ac2d-9bde0a41ce86
            warning: null
            width: 100
        name: Content
        uid: 02c42cc2-9cad-4cb4-b14c-7f23cb4a485a
fields:
  510eb9fd-46de-4aa4-8f10-4282c0fb4de8: # Inhoud
    columnSuffix: fnmbnphn
    contentColumnType: text
    fieldGroup: null
    handle: ttContent
    instructions: null
    name: Inhoud
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  ab3e3d3a-debc-42ca-a231-3766789addd3: # Titel
    columnSuffix: fbzdvulk
    contentColumnType: text
    fieldGroup: null
    handle: ttTitle
    instructions: null
    name: Titel
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: titleTextBlock
name: 'Titel tekstblok'
sortOrder: 1
