field: 42753f56-881c-4d30-82a4-7062d713de9b # Contentbuilder
fieldLayouts:
  de764d14-31a1-49aa-a17b-e479d7e5f412:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a23ff9f1-8080-478b-ac20-7f87e1dd10f5 # Titel
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f7708f16-b45f-4e1d-8e52-897cf2c19b4c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8b253743-df16-4b9b-bc0f-1dd56e117bf1 # URL
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a0b376d4-c1e3-4898-8523-6e596ac0e89d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cdbcd49b-120d-44b0-8eb8-ec5dd64181b1 # Achtergrondkleur
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b066c9d8-3bfc-44b3-92e4-9b7b208f3462
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2e565505-a061-4ee2-826d-915d4c4d0fb7
        userCondition: null
fields:
  8b253743-df16-4b9b-bc0f-1dd56e117bf1: # URL
    columnSuffix: vuqkjuip
    contentColumnType: string(255)
    fieldGroup: null
    handle: videoUrl
    instructions: 'Vul hier de link naar de YouTube of Vimeo URL op.'
    name: URL
    searchable: false
    settings:
      maxLength: 255
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  a23ff9f1-8080-478b-ac20-7f87e1dd10f5: # Titel
    columnSuffix: uhtevawo
    contentColumnType: text
    fieldGroup: null
    handle: blockTitle
    instructions: null
    name: Titel
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  cdbcd49b-120d-44b0-8eb8-ec5dd64181b1: # Achtergrondkleur
    columnSuffix: wrhzjqja
    contentColumnType: string
    fieldGroup: null
    handle: bgColor
    instructions: 'Selecteer een kleur voor de achtergrond van dit blok'
    name: Achtergrondkleur
    searchable: false
    settings:
      dataSet: 'Background colors'
      type: dropdown
    translationKeyFormat: null
    translationMethod: none
    type: statikbe\configvaluesfield\fields\ConfigValuesFieldField
handle: video
name: Video
sortOrder: 7
