data:
  dataRetention: forever
  dataRetentionValue: ''
  fileUploadsAction: retain
  notifications:
    -
      attachFiles: true
      attachPdf: false
      bcc: null
      cc: null
      conditions: '{"sendRule":"send","conditionRule":"all","conditions":[]}'
      content: '[{"type":"paragraph","content":[{"type":"text","text":"A user submission has been made on the \""},{"type":"variableTag","attrs":{"label":"Form Name","value":"{formName}"}},{"type":"text","text":"\" form on "},{"type":"variableTag","attrs":{"label":"Site Name","value":"{siteName}"}},{"type":"text","text":" at "},{"type":"variableTag","attrs":{"label":"Timestamp (yyyy-mm-dd hh:mm:ss)","value":"{timestamp}"}}]},{"type":"paragraph","content":[{"type":"text","text":"Their submission details are:"}]},{"type":"paragraph","content":[{"type":"variableTag","attrs":{"label":"All Form Fields","value":"{allFields}"}}]}]'
      enableConditions: false
      enabled: true
      formId: null
      from: '{field.emailAddress}'
      fromName: null
      id: new981-8077
      name: 'Admin Notification'
      pdfTemplateId: null
      recipients: email
      replyTo: '{field.emailAddress}'
      replyToName: null
      subject: 'A new submission was made on "{formName}"'
      templateId: null
      to: '{systemEmail}'
      toConditions: '{"toRecipients":[]}'
      uid: null
    -
      attachFiles: true
      attachPdf: false
      bcc: null
      cc: null
      conditions: '{"sendRule":"send","conditionRule":"all","conditions":[]}'
      content: '[{"type":"paragraph","content":[{"type":"text","text":"Thanks again for contacting us. Our team will get back to you as soon as we can."}]},{"type":"paragraph","content":[{"type":"text","text":"As a reminder, you submitted the following details at "},{"type":"variableTag","attrs":{"label":"Timestamp (yyyy-mm-dd hh:mm:ss)","value":"{timestamp}"}}]},{"type":"paragraph","content":[{"type":"variableTag","attrs":{"label":"All Form Fields","value":"{allFields}"}}]}]'
      enableConditions: false
      enabled: true
      formId: null
      from: null
      fromName: null
      id: new7052-5168
      name: 'User Notification'
      pdfTemplateId: ''
      recipients: email
      replyTo: null
      replyToName: null
      subject: 'Thanks for contacting us!'
      templateId: ''
      to: '{field.emailAddress}'
      toConditions: '{"toRecipients":[]}'
      uid: null
  pages:
    -
      id: new1272610411
      label: 'Page 1'
      notificationFlag: true
      rows:
        -
          fields:
            -
              brandNewField: false
              columnWidth: 12
              handle: naam
              hasLabel: true
              id: new1870134881
              isNested: false
              label: Naam
              settings:
                handle: naam
                instructionsPosition: ''
                label: Naam
                labelPosition: ''
                maxType: characters
                minType: characters
                required: true
                visibility: ''
              type: verbb\formie\fields\formfields\SingleLineText
              vid: new3574-1561
          id: new9179-3311
        -
          fields:
            -
              brandNewField: false
              handle: emailAddress
              hasLabel: true
              id: new6482-9528
              label: E-mailadres
              settings:
                handle: emailAddress
                instructions: ''
                instructionsPosition: ''
                label: E-mailadres
                labelPosition: ''
                maxType: characters
                placeholder: ''
                required: true
                visibility: ''
              type: verbb\formie\fields\formfields\Email
              vid: new5534-3599
          id: new9524-8509
        -
          fields:
            -
              brandNewField: false
              handle: message
              hasLabel: true
              id: new982-7322
              label: Bericht
              settings:
                conditions: '{"showRule":"show","conditionRule":"all","conditions":[]}'
                handle: message
                instructions: ''
                instructionsPosition: ''
                label: Bericht
                labelPosition: ''
                maxType: characters
                placeholder: ''
                required: true
                visibility: ''
              type: verbb\formie\fields\formfields\MultiLineText
              vid: new3624-1917
          id: new2177-9685
        -
          fields:
            -
              brandNewField: false
              columnWidth: 12
              handle: privacy
              hasLabel: true
              id: new796461951
              isNested: false
              label: Privacy
              settings:
                checkedValue: 'Yes'
                defaultValue: false
                description: '[{"type":"paragraph","attrs":{"textAlign":"start"},"content":[{"type":"text","text":"Ik heb het "},{"type":"text","marks":[{"type":"link","attrs":{"href":"https://alpinedigital.local.alpinedigital.be/nl/privacybeleid#entry:13@1","target":"","class":null}}],"text":"privacy beleid"},{"type":"text","text":" gelezen en goedgekeurd."}]}]'
                handle: privacy
                instructionsPosition: ''
                label: Privacy
                labelPosition: verbb\formie\positions\Hidden
                required: true
                uncheckedValue: 'No'
              type: verbb\formie\fields\formfields\Agree
              vid: new4902-7503
          id: new7135-9967
      settings:
        backButtonLabel: Back
        buttonsPosition: left
        label: 'Page 1'
        showBackButton: false
        submitButtonLabel: 'Contacteer ons'
      sortOrder: 0
  settings:
    collectIp: false
    collectUser: false
    dataRetention: null
    dataRetentionValue: null
    defaultEmailTemplateId: null
    defaultInstructionsPosition: verbb\formie\positions\AboveInput
    defaultLabelPosition: verbb\formie\positions\AboveInput
    disableCaptchas: false
    displayCurrentPageTitle: false
    displayFormTitle: false
    displayPageProgress: false
    displayPageTabs: false
    errorMessage: '[{"type":"paragraph","attrs":{"textAlign":"start"},"content":[{"type":"text","text":"Couldn’t save submission due to errors."}]}]'
    errorMessagePosition: top-form
    fileUploadsAction: null
    integrations:
      honeypot:
        enabled: ''
        showAllPages: ''
      javascript:
        enabled: ''
        showAllPages: ''
    limitSubmissions: false
    limitSubmissionsMessage: '[{"type":"paragraph","attrs":{"textAlign":"start"}}]'
    limitSubmissionsNumber: null
    limitSubmissionsType: total
    loadingIndicator: spinner
    loadingIndicatorText: null
    progressPosition: end
    redirectUrl: null
    requireUser: false
    requireUserMessage: '[{"type":"paragraph","attrs":{"textAlign":"start"}}]'
    scheduleForm: false
    scheduleFormEnd: null
    scheduleFormExpiredMessage: '[{"type":"paragraph","attrs":{"textAlign":"start"}}]'
    scheduleFormPendingMessage: '[{"type":"paragraph","attrs":{"textAlign":"start"}}]'
    scheduleFormStart: null
    scrollToTop: true
    submissionTitleFormat: '{timestamp}'
    submitAction: message
    submitActionFormHide: false
    submitActionMessage: '[{"type":"paragraph","attrs":{"textAlign":"start"},"content":[{"type":"text","text":"Thank you for contacting us! Our team will get in touch shortly to follow up on your message."}]}]'
    submitActionMessagePosition: top-form
    submitActionMessageTimeout: null
    submitActionTab: null
    submitActionUrl: null
    submitMethod: ajax
    validationOnFocus: true
    validationOnSubmit: true
  userDeletedAction: retain
defaultStatus: 74fff7e2-1518-4daa-bcd2-229e688b6876 # New
handle: contactForm
name: 'Contact Form'
submitActionEntry: null
template: null
