fieldLayouts:
  0de03e0f-b4d9-4d14-8f7d-08b006e823d1:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: bcc46a7b-bdd2-4ffa-b898-bf9ad5cb0583
            warning: null
            width: 100
          -
            fieldUid: fd367c18-3448-4df5-b70e-af6f48bf0c4c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bf3b7386-a8e7-4f37-9f3b-335ef21bee2a
            warning: null
            width: 100
        name: Content
        uid: acc86ddc-7895-44bc-b619-697e9b7069d7
handle: defaultHtml
hasTitleField: true
name: 'Default HTML styling'
section: aea891e5-7577-41f6-a827-258037235a16 # Default HTML styling
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
