fieldLayouts:
  f204b01d-3def-4a9f-ac35-17d807ef755c:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f825b8e1-6a19-44db-bc30-358e712155c5
            warning: null
            width: 100
        name: Content
        uid: 27423f74-14dc-4dd2-b334-1eb191113317
handle: default
hasTitleField: true
name: Default
section: 298e299b-a244-47dd-8420-45bf6e1c3f4e # Doelgroepen
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
