fieldLayouts:
  0e4eb0fe-0f0f-4673-a37e-a7f3e74acba4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 16bc0001-57cd-4c80-9222-fbcf703edc8b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b693e790-e464-467a-81a1-f62bb9914cb2 # Hero afbeelding
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8b1ca898-d903-4783-809d-783d551b0017
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: e57c50c0-e93d-4551-afbc-bfccd8274f8d # Wijzig weergave
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7d537206-d150-4808-bfe5-5169c7479e1e
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 71121d32-13d9-4173-b4d5-cb96fb596e4d # Intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 16a73df2-d8df-4250-b9b8-d9f0f8b0ee71
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2a7635da-9798-4a72-9262-84d14e66931f # Call to action(s)
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1ff4e81e-7d4f-4190-b493-99e060dd1240
            userCondition: null
            warning: null
            width: 100
        name: Hero
        uid: bc889d5b-a964-4cd7-8c05-632a283e55a5
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 42753f56-881c-4d30-82a4-7062d713de9b # Contentbuilder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8cbd844f-8549-4da5-a1eb-4ff59542b655
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: 4e3ddd67-391e-4293-b4be-5f0b8d5cea67
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c7e33047-eed9-474f-b8e4-80a1945b1f57 # Overview Titel
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 47c6c686-a6fd-4436-b4c9-aeb460df19d2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 67058d8b-b679-4c50-96fc-9e21366eea0c # Overview Omschrijving
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9cb20a16-2137-4859-a1c8-e56f1b26110b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2ed0506e-2d1d-4f21-a387-92dcc5cf64f7 # Overview Afbeelding
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ac415c1d-0aba-4151-927c-391bb8ff63a2
            userCondition: null
            warning: null
            width: 100
        name: Overview
        uid: 563e69bd-e594-4fad-bd46-ae5145386718
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 87757b92-04cd-4915-971d-e0d100fccb17 # SEO instellingen
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 909b94df-73ac-4705-ba31-6268c0fdabc3
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 1e303f26-3b8b-4ecc-bcff-c152fc1041dd
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 14ff9459-9619-4a01-9cbb-c9614a846858 # Pagina's
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{heroTitle|striptags}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
