fieldLayouts:
  c90cac58-bc7e-4cc6-97a0-1315829b1f6a:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 27a33f3b-bfdb-47b5-9b08-a3993250bcb4
            warning: null
            width: 100
          -
            fieldUid: 923e90c0-ecae-4bbc-97eb-6cc3136a8cd1 # Banner intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4481fb16-bee4-46d9-98b2-e3b2d05e84bd
            warning: null
            width: 50
          -
            fieldUid: 1c629b66-cd2f-4da6-85a4-72e69772ba1e # Banner afbeelding
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f32faff2-916a-4222-8c07-8583c18fc86e
            warning: null
            width: 50
        name: Banner
        uid: acdb1102-bbce-431f-99d8-af312bb9d9ec
      -
        elements:
          -
            fieldUid: 073500d7-f6ec-444e-8f0a-650eaa803cb0 # Titel | Tekstblok
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 68abe69d-b2c0-4e51-803e-473fa6510988
            warning: null
            width: 100
        name: Inhoud
        uid: 87a9d904-b655-4788-bdcd-8d304cfe8776
      -
        elements:
          -
            fieldUid: 187580b7-6dbe-4d63-ab88-5288f10e41aa # Handige links
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4a4f6cdf-91c7-4214-a2f2-e8101d482397
            warning: null
            width: 50
        name: 'Handige linken'
        uid: 6c472c19-2b57-4965-8723-703d135f43c3
      -
        elements:
          -
            fieldUid: 39aadce1-b28b-45e1-b7e0-fdfa779db19f # PDF 
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8a54dca4-3eec-480a-ab83-93bc92f51f4c
            warning: null
            width: 50
        name: 'Handige documenten'
        uid: 102b046e-d17d-4424-849d-0c931c31369e
handle: default
hasTitleField: true
name: Default
section: 5a50b43e-57ff-451d-99a9-6e517f9d600d # Over ons
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
