fieldLayouts:
  26e4c6db-292d-44e2-b9c0-4459ef88220d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: Titel
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 17830e10-dd8c-4016-adec-9893a00cce02
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b693e790-e464-467a-81a1-f62bb9914cb2 # Hero afbeelding
            instructions: "Laadt hier een vector illustratie op. \r\nDeze zal in zijn geheel getoond worden en wijkt af van de andere hero's."
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: da0a9e20-510c-4b56-9a95-5ffff7b3bdcb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 71121d32-13d9-4173-b4d5-cb96fb596e4d # Intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6ab32a60-1234-4277-854e-561c9e91589e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2a7635da-9798-4a72-9262-84d14e66931f # Call to action(s)
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 179170dc-122e-4ae3-8920-38b6c40c6663
            userCondition: null
            warning: null
            width: 100
        name: Hero
        uid: fc953bb6-00c6-411f-9e2f-1fbef4431bca
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 42753f56-881c-4d30-82a4-7062d713de9b # Contentbuilder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e96e6280-6d24-4a97-ac66-6fafbadabf0b
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: a80c8154-86de-439b-9bed-c487358ceaa8
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 87757b92-04cd-4915-971d-e0d100fccb17 # SEO instellingen
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6abaa173-5f8f-470f-8217-b243e2230ac0
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: bac43ead-9f93-49d1-8a1a-44e663bdc3d5
        userCondition: null
handle: servicesOverview
hasTitleField: true
name: 'Werking Overzicht'
section: e782c6a6-d9c0-413a-8058-4f24bd7ff518 # Werking Overzicht
sortOrder: 1
titleFormat: '{pageTitle|striptags}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
