fieldLayouts:
  b4635109-bd41-4579-9ca2-b9feed6bac6a:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c6558ebc-fde2-4785-a92b-eec0fb475982
            warning: null
            width: 100
          -
            fieldUid: 923e90c0-ecae-4bbc-97eb-6cc3136a8cd1 # Banner intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 625be346-d10e-4206-9235-5fca28e8401a
            warning: null
            width: 50
          -
            fieldUid: 1c629b66-cd2f-4da6-85a4-72e69772ba1e # Banner afbeelding
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b0b6e108-49e0-41b1-8eca-60262f25349e
            warning: null
            width: 50
        name: Banner
        uid: d8420d70-7051-4db0-8658-316b19121ccb
      -
        elements:
          -
            fieldUid: b87f3585-f683-47d2-a221-4457003d89f8 # Titel | Tekstblok | Afbeelding
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: edb99915-7def-4ac9-a961-acb72d6f45c6
            warning: null
            width: 100
        name: Inhoud
        uid: 8d560b82-53b4-48a4-ade8-688efecfe8e0
handle: vacancies
hasTitleField: true
name: 'Werken bij d.a.t.'
section: 1a5e8394-ba57-4463-b046-6c9de0812b2c # Werken bij d.a.t.
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
