defaultPlacement: end
fieldLayouts:
  8bab5141-bd0f-490d-90e7-a4db0a4c5b17:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: a27da586-c0a4-44af-a2e7-38298654fbbf
            warning: null
            width: 100
          -
            fieldUid: a29019e4-2a19-4028-98c9-ffe999e1475b # Afbeelding
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a4337416-5dbd-4003-82f3-d6f235d92036
            warning: null
            width: 100
          -
            fieldUid: 2ac35130-5421-4b13-98e9-916fc6c5c9c3 # Beschrijving
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6d0c385b-6259-4e5e-a8dc-d5b5e61e545d
            warning: null
            width: 100
        name: Content
        uid: 3af730aa-7ba9-418a-85f0-2424cac020c8
handle: targetGroups
name: Doelgroepen
siteSettings:
  7fb1be39-cc20-49d5-8628-889003e31f09: # fr
    hasUrls: true
    template: null
    uriFormat: 'doelgroepen/{slug}'
  33b9a6a8-f771-4a59-a8d6-4800dc41bc2d: # nl
    hasUrls: true
    template: null
    uriFormat: 'doelgroepen/{slug}'
  e38d253f-b5c1-457e-925f-2670c4704eb1: # en
    hasUrls: true
    template: null
    uriFormat: 'doelgroepen/{slug}'
structure:
  maxLevels: null
  uid: cebcb6d3-d22b-4a23-8185-4e28b751bb1f
