fieldLayouts:
  509da2b2-9b3b-419a-87f0-442696c5af2a:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: e034c4de-eb00-4412-8cf5-4318f1b576f6
            warning: null
            width: 100
        name: Content
        uid: 2ff0d5e6-8a00-415e-a73b-d76a89cf535c
fs: bannerImages
handle: bannerImages
name: 'Banner afbeeldingen'
sortOrder: 5
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: bannerImages
transformSubpath: ''
