fieldLayouts:
  698b6bd6-9530-417c-8045-34fa019dd21b:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: ef1a5b4a-6a02-44b4-9a16-ec2a8cf7f556
            warning: null
            width: 100
        name: Content
        uid: cf456820-e864-48fd-9ffc-1656ee6a990a
fs: pdf
handle: pdf
name: PDF
sortOrder: 7
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
