fieldLayouts:
  abe64ee4-160b-4a8e-93dc-9c7e0399ed4c:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 43a45929-9fa2-47e2-895a-3d86339a6229
            warning: null
            width: 100
        name: Content
        uid: b67efa12-2f88-4fc8-bbfc-ae7f9f7340bc
fs: sponsors
handle: sponsors
name: Sponsors
sortOrder: 3
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: sponsors
transformSubpath: ''
