columnSuffix: zmrssdiy
contentColumnType: string
fieldGroup: fee593e7-c65b-45c3-9d81-a9c4a1863566 # Footer
handle: contactFooter
instructions: null
name: Contactgegevens
searchable: false
settings:
  contentTable: '{{%matrixcontent_contactfooter}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
