columnSuffix: null
contentColumnType: string
fieldGroup: 2c52ece1-d061-4a11-a044-57da62f1528e # Contentbuilder
handle: contentBuilder
instructions: 'Met dit veld kan je verschillende blokken toevoegen aan de pagina om deze naar wens vorm te geven'
name: Contentbuilder
searchable: true
settings:
  contentTable: '{{%matrixcontent_contentbuilder}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
