columnSuffix: vyyopgrj
contentColumnType: string(255)
fieldGroup: ee71a197-2900-41c3-8ede-20b5bc467852 # Common
handle: linkIt
instructions: null
name: Link
searchable: false
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
