columnSuffix: scwlupzi
contentColumnType: string(255)
fieldGroup: 1ed7efa2-b8da-4da5-8c3a-6c98c05577b0 # Common
handle: linkIt
instructions: null
name: Link
searchable: true
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
