columnSuffix: null
contentColumnType: string
fieldGroup: 1ed7efa2-b8da-4da5-8c3a-6c98c05577b0 # Common
handle: locationBlock
instructions: null
name: Locatie
searchable: false
settings:
  contentTable: '{{%matrixcontent_locationblock}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
