columnSuffix: null
contentColumnType: string
fieldGroup: 95eab332-7029-4034-8a53-0221d3f797ca # Link / PDF blokken
handle: pdf
instructions: null
name: 'PDF '
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - pdf
  defaultUploadLocationSource: 'volume:fdb9bfff-e48f-424c-b268-d852e14a76ff' # Sponsors
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:fdb9bfff-e48f-424c-b268-d852e14a76ff' # Sponsors
  restrictedLocationSubpath: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
  selectionLabel: null
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  source: null
  sources:
    - 'volume:fe6e5ae7-1535-49f3-ba12-588b4fc92e39' # PDF
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
