columnSuffix: iuawryrn
contentColumnType: text
fieldGroup: 0ae41f7b-646b-4f66-8dad-e8411d392412 # Contactgegevens
handle: streetNr
instructions: null
name: 'Straat + nr'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
