changedFieldIndicator: 721679289
field: bb317d1b-5538-4863-a5c8-68fe6e33d992 # Call to action(s)
fieldLayouts:
  2803b9e9-d619-429b-b704-bdd7ddc0c83e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d791a274-27da-4bcb-bc20-dd381cec644b # Call to action
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1b31b805-c35a-4f8c-9313-bd469e77d6b2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2bfb5db2-d88d-4761-a6aa-fd4aee94c038
        userCondition: null
fields:
  d791a274-27da-4bcb-bc20-dd381cec644b: # Call to action
    columnSuffix: mblrtrsy
    contentColumnType: text
    fieldGroup: null
    handle: cta
    instructions: 'Geef hier een call to action in.'
    name: 'Call to action'
    searchable: true
    settings:
      allowClass: '1'
      allowCustomText: '1'
      allowTarget: '1'
      allowedLinkNames:
        1: asset
        3: entry
        4: email
        5: tel
        6: url
      class: null
      classes: null
      defaultLinkName: entry
      defaultText: ''
      typeSettings:
        __assoc__:
          -
            - asset
            -
              __assoc__:
                -
                  - sources
                  - '*'
          -
            - category
            -
              __assoc__:
                -
                  - sources
                  - '*'
          -
            - entry
            -
              __assoc__:
                -
                  - sources
                  - '*'
          -
            - email
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
          -
            - tel
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
          -
            - url
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
    translationKeyFormat: null
    translationMethod: none
    type: statikbe\cta\fields\CTAField
