changedFieldIndicator: 867857951
field: 501f3d96-f29b-43ff-b392-abc0e4951179 # Call to action(s)
fieldLayouts:
  c0d2a3e0-fe80-491a-a40b-032923e94bc9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 540766f2-cd4c-4b87-980c-d1449f2e1601 # Call to action
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e4723809-0bc7-41ad-8b03-33b516df436e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e0f8ec48-e550-49a1-80b2-f20a3c628e75
        userCondition: null
fields:
  540766f2-cd4c-4b87-980c-d1449f2e1601: # Call to action
    columnSuffix: qemaekgz
    contentColumnType: text
    fieldGroup: null
    handle: cta
    instructions: null
    name: 'Call to action'
    searchable: true
    settings:
      allowClass: '1'
      allowCustomText: '1'
      allowTarget: '1'
      allowedLinkNames:
        1: asset
        3: entry
        4: email
        5: tel
        6: url
      class: null
      classes: null
      defaultLinkName: entry
      defaultText: ''
      typeSettings:
        __assoc__:
          -
            - asset
            -
              __assoc__:
                -
                  - sources
                  - '*'
          -
            - category
            -
              __assoc__:
                -
                  - sources
                  - '*'
          -
            - entry
            -
              __assoc__:
                -
                  - sources
                  - '*'
          -
            - email
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
          -
            - tel
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
          -
            - url
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
    translationKeyFormat: null
    translationMethod: none
    type: statikbe\cta\fields\CTAField
