changedFieldIndicator: 1153483127
field: a23c097e-fea2-479e-8d86-3e986c99ad54 # Call to action(s)
fieldLayouts:
  f1f5d04f-9932-4597-81fb-44b651ee5949:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 49811070-72ae-4f54-9647-de515b8389d3 # Call to action
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cc238ede-cc99-4ebc-a17a-4794270f17ea
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 24986b44-0615-424a-8937-381974bec3d5
        userCondition: null
fields:
  49811070-72ae-4f54-9647-de515b8389d3: # Call to action
    columnSuffix: ngmokqqs
    contentColumnType: text
    fieldGroup: null
    handle: cta
    instructions: null
    name: 'Call to action'
    searchable: true
    settings:
      allowClass: '1'
      allowCustomText: '1'
      allowTarget: '1'
      allowedLinkNames:
        1: asset
        3: entry
        4: email
        5: tel
        6: url
      class: null
      classes: null
      defaultLinkName: entry
      defaultText: ''
      typeSettings:
        __assoc__:
          -
            - asset
            -
              __assoc__:
                -
                  - sources
                  - '*'
          -
            - category
            -
              __assoc__:
                -
                  - sources
                  - '*'
          -
            - entry
            -
              __assoc__:
                -
                  - sources
                  - '*'
          -
            - email
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
          -
            - tel
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
          -
            - url
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
    translationKeyFormat: null
    translationMethod: none
    type: statikbe\cta\fields\CTAField
