changedFieldIndicator: 1781515798
field: 2e347f7c-204d-4a1d-8ce2-8440ee9627bf # Overview
fieldLayouts:
  3ca7d1c9-84df-4a6d-aee5-d41cb640b228:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8d5a9c57-28fe-4acd-9a1d-e37eb3a7f255 # Titel
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 550d14c8-1de5-4294-ad40-8afef5abf95e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2ba01606-3cdb-4961-b59c-f639c3b302e5 # Tekst
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5eded778-a689-4fe8-8f02-6c9b32f99c41
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dfdf807c-3b94-4a5d-97e0-6b426d765b64 # Afbeelding
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8d734cd0-db45-47c1-96be-8addb43e3af8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 92f319dc-dd27-4c9b-9d05-b14db0dff1de
        userCondition: null
fields:
  2ba01606-3cdb-4961-b59c-f639c3b302e5: # Tekst
    columnSuffix: aufwiant
    contentColumnType: text
    fieldGroup: null
    handle: overviewRedactor
    instructions: null
    name: Tekst
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  8d5a9c57-28fe-4acd-9a1d-e37eb3a7f255: # Titel
    columnSuffix: mndhwkna
    contentColumnType: text
    fieldGroup: null
    handle: overviewTitle
    instructions: 'Geef hier de titel in van de USP'
    name: Titel
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  dfdf807c-3b94-4a5d-97e0-6b426d765b64: # Afbeelding
    columnSuffix: eqjpjzlg
    contentColumnType: string
    fieldGroup: null
    handle: overviewImage
    instructions: null
    name: Afbeelding
    searchable: true
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: false
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:65b2bb5a-5270-45fc-a215-72c888b19334' # Bestanden
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:65b2bb5a-5270-45fc-a215-72c888b19334' # Bestanden
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
