fieldLayouts:
  3a4e23c9-336c-4dbf-bbf1-0965e7e9870b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d6893358-6209-49d3-aacd-4c70217b3636 # Instagram
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e6777863-35e9-422c-a7a0-696270fc88a4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1009e391-2098-414e-ac2b-15c879524850
        userCondition: null
handle: contactInfo
name: Contacgegevens
sortOrder: 3
