fieldLayouts:
  7e00e89c-57bd-4dd4-8487-711d38ecfd33:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: cc9be780-1445-4090-9b31-2c7fe893e319 # Centra
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 52d113b0-d42f-43df-824d-07f1fdd2c7c1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f74fd121-7c41-410e-af32-8cae629363d2 # Bedrijfsnaam
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3e01bf1b-6dc1-43cd-9838-92cc0aebf6a1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 444c47d1-963d-48a1-9a07-58f96da02792 # Straat + nr
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5eed40d1-e74e-47a3-a99d-4b2c4aecf437
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c6df9fe5-084d-496b-a95b-deaed4b8f903 # Postcode
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3c64ca1c-f697-431e-b602-f00f262c02e7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1c312155-420e-4220-b303-c671c5b60f13 # Stad / gemeente
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 069861fe-a0d8-4f69-936b-4d1bee4b8339
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4f7309dc-2fea-46ab-9a22-d6e095e22bc3 # Telefoonnummer
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0dede560-5cb0-4b45-a1ce-725bd8f756f3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f45e22b0-5213-485f-bad1-a18b90979aea # E-mailadres
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 150cd989-bf22-4d3a-8dbc-9d875d3aa747
            userCondition: null
            warning: null
            width: 100
        name: Gegevens
        uid: 4ab4e089-a0ac-4467-9720-0d6a62d8efb9
        userCondition: null
handle: contactDetails
name: Contactgegevens
sortOrder: 2
