fieldLayouts:
  8fdfde74-0b89-4382-ab88-8e07da343f47:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e9085f02-1b94-4e21-a749-2d0e683c6d8b # Link
            instructions: 'Geef hier de link in die moet leiden naar de afgeschermde omgeving. De link wordt gebruikt bij de ''Inloggen'' knop in de service navigatie.'
            label: 'Link naar afgeschermde omgeving'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e5157c1f-2c19-4a1b-b67e-7ebd941001e6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 87f7ee66-4f1f-463d-a61f-6673e016b093
        userCondition: null
handle: other
name: Andere
sortOrder: 4
