defaultPlacement: end
enableVersioning: true
handle: blog
name: Blog
propagationMethod: all
siteSettings:
  753d678c-4018-409d-9dfa-5c4fdc2219b7: # Dat vzw
    enabledByDefault: true
    hasUrls: true
    template: _pages/_blog/_entry.twig
    uriFormat: 'blog/{slug}'
structure:
  maxLevels: 1
  uid: 391cc616-78ac-40f5-a3b7-6d49c9dbb604
type: structure
