defaultPlacement: end
enableVersioning: true
handle: cookiePolicy
name: Cookiebeleid
propagationMethod: all
siteSettings:
  753d678c-4018-409d-9dfa-5c4fdc2219b7: # Dat vzw
    enabledByDefault: true
    hasUrls: true
    template: _pages/_content-page.twig
    uriFormat: cookiebeleid
type: single
