defaultPlacement: end
enableVersioning: true
handle: home
name: Homepage
propagationMethod: all
siteSettings:
  753d678c-4018-409d-9dfa-5c4fdc2219b7: # Dat vzw
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
