defaultPlacement: end
enableVersioning: true
handle: jobs
name: Vacatures
propagationMethod: all
siteSettings:
  753d678c-4018-409d-9dfa-5c4fdc2219b7: # Dat vzw
    enabledByDefault: true
    hasUrls: true
    template: _pages/_jobs/_entry.twig
    uriFormat: 'vacatures/{slug}'
structure:
  maxLevels: 1
  uid: cf43eeba-d378-4d7c-a8b1-b638117f94bf
type: structure
