defaultPlacement: end
enableVersioning: true
handle: jobs
name: Vacatures
propagationMethod: all
siteSettings:
  753d678c-4018-409d-9dfa-5c4fdc2219b7: # Dat vzw
    enabledByDefault: true
    hasUrls: true
    template: _pages/_jobs/_entry.twig
    uriFormat: 'vacatures/{slug}'
type: channel
