defaultPlacement: end
enableVersioning: true
handle: services
name: Werking
propagationMethod: all
siteSettings:
  753d678c-4018-409d-9dfa-5c4fdc2219b7: # Dat vzw
    enabledByDefault: true
    hasUrls: true
    template: _pages/_services/_entry.twig
    uriFormat: 'onze-werking/{slug}'
structure:
  maxLevels: null
  uid: ec887ad1-7cbc-4731-9c7d-12e441e0cacd
type: structure
