defaultPlacement: end
enableVersioning: true
handle: vacancies
name: 'Werken bij d.a.t.'
propagationMethod: all
siteSettings:
  7fb1be39-cc20-49d5-8628-889003e31f09: # fr
    enabledByDefault: true
    hasUrls: true
    template: _pages\_vacancies\_index.html.twig
    uriFormat: '{parent.uri}/{slug}'
  33b9a6a8-f771-4a59-a8d6-4800dc41bc2d: # nl
    enabledByDefault: true
    hasUrls: true
    template: _pages\_vacancies\_index.html.twig
    uriFormat: '{parent.uri}/{slug}'
  e38d253f-b5c1-457e-925f-2670c4704eb1: # en
    enabledByDefault: true
    hasUrls: true
    template: _pages\_vacancies\_index.html.twig
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: fee6a421-6996-4eb2-b182-8586c6baf0d4
type: structure
