handle: alpineDigital
name: 'Alpine Digital'
outputCssLayout: false
outputCssLocation: page-header
outputCssTheme: false
outputJsBase: true
outputJsLocation: inside-form
outputJsTheme: true
sortOrder: null
template: ''
useCustomTemplates: false
